// multi-tenant/frontend/src/pages/auth/LoginPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { cn } from "$lib/utils";
  import { Button } from "$components/ui/button";
  import { Input } from "$components/ui/input";
  import { Checkbox } from "$components/ui/checkbox";
  import { Spinner } from "$components/ui/spinner";
  import { MovaLogo } from "$components/ui/brand";
  import { DotPattern } from "$components/ui/dot-pattern";
  import { authService, type CaptchaData } from "../../services/authService";
  import { authStore, getRoleLandingPath } from "../../lib/stores/auth.svelte";
  import { setupStore } from "../../lib/stores/setupStore.svelte";
  import { router } from "../../lib/stores/router.svelte";
  import { Shield } from "lucide-svelte";

  interface Props {
    onNavigate?: (path: string) => void;
  }

  let { onNavigate }: Props = $props();

  let identifier = $state("");
  let password = $state("");
  let rememberMe = $state(true);
  let showPassword = $state(false);
  let isLoading = $state(false);
  let errorMessage = $state("");

  // Captcha state
  let captcha = $state<CaptchaData | null>(null);
  let captchaAnswer = $state("");
  let requiresCaptcha = $state(false);
  let captchaLoading = $state(false);

  const fetchCaptcha = async () => {
    captchaLoading = true;
    try {
      const data = await authService.getCaptcha(captcha?.captcha_id);
      captcha = data;
      requiresCaptcha = true;
    } catch (err: any) {
      console.warn("Gagal memuat captcha:", err);
    } finally {
      captchaLoading = false;
    }
  };

  const navigateTo = (path: string) => {
    if (onNavigate) {
      onNavigate(path);
    } else {
      router.navigate(path);
    }
  };

  onMount(async () => {
    try {
      const risk = await authService.checkRiskStatus();
      if (risk.requires_captcha) {
        await fetchCaptcha();
      }
    } catch {
      // Risk check non-blocking
    }
  });

  async function handleLogin(e: Event) {
    e.preventDefault();
    if (!identifier || !password) {
      errorMessage = "Silakan masukkan email/username dan password Anda.";
      return;
    }

    if (requiresCaptcha && !captchaAnswer.trim()) {
      errorMessage = "Silakan masukkan kode CAPTCHA yang tampil pada gambar.";
      return;
    }

    errorMessage = "";
    isLoading = true;

    try {
      const res = await authService.login({
        identifier: identifier.trim(),
        password,
        captcha_id: captcha?.captcha_id,
        captcha_answer: captchaAnswer.trim() || undefined,
      });

      authStore.login(res.user, res.token, res.refreshToken);

      if (res.user.first_login) {
        navigateTo("/first-login");
      } else if (res.user.role === "SUPERADMIN") {
        const setup = await setupStore.checkStatus();
        if (setup && (setup.status === "REQUIRED" || setup.status === "IN_PROGRESS")) {
          navigateTo("/first-setup");
        } else {
          navigateTo("/dashboard");
        }
      } else {
        const destination = getRoleLandingPath(res.user.role);
        navigateTo(destination);
      }
    } catch (err: any) {
      const resData = err?.response?.data;
      if (
        resData?.requires_captcha ||
        resData?.code === "CAPTCHA_REQUIRED" ||
        resData?.code === "CAPTCHA_INVALID" ||
        (err?.response?.status === 400 &&
          (String(resData?.msg || "")
            .toLowerCase()
            .includes("captcha") ||
            String(resData?.message || "")
              .toLowerCase()
              .includes("captcha")))
      ) {
        requiresCaptcha = true;
        await fetchCaptcha();
        captchaAnswer = "";
      }
      errorMessage =
        resData?.msg ||
        resData?.message ||
        err?.message ||
        "Gagal masuk ke sistem. Periksa kembali kredensial Anda.";
    } finally {
      isLoading = false;
    }
  }
</script>

<div
  class="relative min-h-screen w-full flex items-center justify-center bg-[#09090b] px-4 py-12 overflow-hidden font-sans selection:bg-[#FF634A]/30"
>
  <!-- Ambient Dot Pattern with Masking -->
  <DotPattern
    class="[mask-image:radial-gradient(800px_circle_at_center,white,transparent)] opacity-40 fill-zinc-500 pointer-events-none"
    width={20}
    height={20}
    cr={1.2}
  />

  <!-- Ambient Radiant Glow Orbs -->
  <div
    class="absolute top-1/4 -left-32 h-96 w-96 rounded-full bg-[#FF634A]/10 blur-[128px] pointer-events-none"
  ></div>
  <div
    class="absolute bottom-1/4 -right-32 h-96 w-96 rounded-full bg-amber-500/10 blur-[128px] pointer-events-none"
  ></div>

  <!-- Background Mova Typography Watermark matching Logo (Heavy & Tight with Dot) -->
  <div
    class="absolute inset-0 flex items-center justify-center pointer-events-none select-none z-0 overflow-hidden"
  >
    <span
      class="font-heading text-[12rem] sm:text-[18rem] md:text-[24rem] font-black tracking-[-0.035em] text-white/[0.045] leading-none select-none"
    >
      Mova<span class="text-[#FF634A]/30">.</span>
    </span>
  </div>

  <!-- Centered Login Card (Level 2 Surface) -->
  <div
    class="relative z-10 w-full max-w-md rounded-3xl border border-white/10 bg-[#131316]/90 p-8 shadow-2xl shadow-black/80 backdrop-blur-xl sm:p-10"
  >
    <!-- Header -->
    <div class="mb-8 text-center">
      <h1
        class="font-heading text-2xl font-bold tracking-tight text-white sm:text-3xl"
      >
        Selamat Datang di Mova<span class="text-[#FF634A]">.</span>
      </h1>
      <p class="text-xs text-zinc-400 font-sans leading-relaxed">
        platform DSS untuk optimasi lokasi penjualan bisnis berbasis keliling
      </p>
    </div>

    {#if errorMessage}
      <div
        class="mb-6 flex items-center gap-2 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-400"
      >
        <i class="bx bx-error-circle text-base"></i>
        <span>{errorMessage}</span>
      </div>
    {/if}

    <!-- Login Form -->
    <form onsubmit={handleLogin} class="space-y-4 font-sans">
      <div>
        <label
          for="identifier"
          class="mb-1.5 block text-xs font-medium text-zinc-300"
        >
          Email / Username
        </label>
        <Input
          id="identifier"
          type="text"
          placeholder="nama@perusahaan.com / NIK"
          icon="bx-envelope"
          bind:value={identifier}
          required
        />
      </div>

      <div>
        <div class="mb-1.5 flex items-center justify-between">
          <label for="password" class="block text-xs font-medium text-zinc-300">
            Password
          </label>
          <button
            type="button"
            onclick={() => navigateTo("/forgot-password")}
            class="text-xs text-[#FF634A] hover:underline cursor-pointer bg-transparent border-0 p-0"
          >
            Lupa Password?
          </button>
        </div>
        <div class="relative">
          <Input
            id="password"
            type={showPassword ? "text" : "password"}
            placeholder="••••••••"
            icon="bx-lock-alt"
            bind:value={password}
            required
          >
            {#snippet suffix()}
              <button
                type="button"
                onclick={() => (showPassword = !showPassword)}
                class="text-zinc-400 hover:text-white cursor-pointer"
                aria-label="Toggle password visibility"
              >
                <i
                  class={cn(
                    "bx text-base",
                    showPassword ? "bx-hide" : "bx-show",
                  )}
                ></i>
              </button>
            {/snippet}
          </Input>
        </div>
      </div>

      <!-- CAPTCHA Verification Block -->
      {#if requiresCaptcha}
        <div
          class="p-3.5 rounded-2xl bg-[#18181D] border border-[#2C2C36] space-y-2.5"
        >
          <div class="flex items-center justify-between">
            <span
              class="text-xs text-zinc-300 font-medium flex items-center gap-1.5"
            >
              <i class="bx bx-shield-quarter text-[#FF634A]"></i>
              Verifikasi Keamanan CAPTCHA
            </span>
            <button
              type="button"
              onclick={fetchCaptcha}
              disabled={captchaLoading}
              class="text-xs text-[#FF634A] hover:underline flex items-center gap-1 cursor-pointer bg-transparent border-0 p-0 disabled:opacity-50"
            >
              <i class="bx bx-refresh {captchaLoading ? 'animate-spin' : ''}"
              ></i>
              Ganti Kode
            </button>
          </div>

          <!-- SVG Image Container -->
          <div
            class="w-full h-12 bg-[#121216] rounded-xl p-1 flex items-center justify-center overflow-hidden border border-[#2C2C36] select-none"
          >
            {#if captchaLoading}
              <div class="flex items-center gap-2 text-xs text-zinc-400">
                <i class="bx bx-loader-alt animate-spin text-[#FF634A]"></i>
                <span>Memuat kode verifikasi...</span>
              </div>
            {:else if captcha?.svg}
              <img
                src={captcha.svg.startsWith("data:") ||
                captcha.svg.startsWith("http")
                  ? captcha.svg
                  : `data:image/svg+xml;utf8,${encodeURIComponent(captcha.svg)}`}
                alt="Kode CAPTCHA"
                class="h-10 w-auto object-contain select-none pointer-events-none filter contrast-125"
              />
            {:else}
              <button
                type="button"
                onclick={fetchCaptcha}
                class="text-xs text-[#FF634A] hover:underline cursor-pointer bg-transparent border-0"
              >
                Klik untuk memuat CAPTCHA
              </button>
            {/if}
          </div>

          <Input
            id="captcha-answer"
            type="text"
            placeholder="Ketik 5 kode huruf/angka di atas..."
            icon="bx-shield-quarter"
            bind:value={captchaAnswer}
            required
          />
        </div>
      {/if}

      <div class="flex items-center justify-between pt-1">
        <label
          class="flex items-center gap-2 text-xs text-zinc-300 cursor-pointer select-none"
        >
          <Checkbox bind:checked={rememberMe} />
          <span>Ingat sesi perangkat ini</span>
        </label>
      </div>

      <Button
        type="submit"
        variant="default"
        size="lg"
        disabled={isLoading}
        class="w-full mt-2 h-11 text-base font-semibold"
      >
        {#if isLoading}
          <Spinner size="sm" class="border-white" />
          <span>Memverifikasi...</span>
        {:else}
          <span>Masuk ke Dashboard</span>
          <i class="bx bx-right-arrow-alt text-xl"></i>
        {/if}
      </Button>
    </form>
    <!-- Footer Note -->
    <div class="pt-2 text-center space-y-1">
      <div
        class="flex items-center justify-center gap-1.5 text-[11px] text-zinc-500 font-medium"
      >
        <Shield class="w-3 h-3 text-zinc-600" />
        <span>Akses Terbatas: Sistem Internal Perusahaan</span>
      </div>
    </div>
  </div>
</div>

// single-tenant/frontend/src/pages/auth/LoginPage.jsx
import React, { useState, useEffect } from "react";
import { useNavigate, useLocation, useSearchParams, Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { useAuthStore } from "@/stores/useAuthStore";
import { useUiStore } from "@/stores/useUiStore";
import { authService } from "@/services/authService";
import { Alert, ThemeToggle } from "@/components/primitives";
import {
  Mail,
  Lock,
  Eye,
  EyeOff,
  ArrowRight,
} from "lucide-react";
import { formatApiError } from "@/lib/errorHandler";

const loginSchema = z.object({
  identifier: z.string().min(1, "Username atau email wajib diisi"),
  password: z.string().min(1, "Kata sandi wajib diisi"),
});

export function LoginPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const [searchParams] = useSearchParams();
  const setAuth = useAuthStore((state) => state.setAuth);
  const { theme } = useUiStore();

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [successNotice, setSuccessNotice] = useState(null);
  const [warningNotice, setWarningNotice] = useState(null);
  const [showPassword, setShowPassword] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      identifier: "",
      password: "",
    },
  });

  useEffect(() => {
    if (searchParams.get("activated") === "true") {
      setSuccessNotice("Akun staf Anda telah berhasil diaktifkan. Silakan login dengan kata sandi baru Anda.");
    } else if (searchParams.get("reset") === "true") {
      setSuccessNotice("Kata sandi berhasil diperbarui. Silakan masuk dengan kredensial baru Anda.");
    } else if (searchParams.get("reason") === "session_expired") {
      setWarningNotice("Sesi login Anda telah berakhir. Silakan masuk kembali untuk melanjutkan.");
    } else if (searchParams.get("reason") === "idle_timeout") {
      setWarningNotice("Sesi Anda telah berakhir karena tidak ada aktivitas. Silakan masuk kembali.");
    }
  }, [searchParams]);

  const onSubmit = async (data) => {
    setLoading(true);
    setError(null);

    try {
      const response = await authService.login({
        username: data.identifier,
        password: data.password,
      });

      setAuth(response.token, response.user, response.refreshToken);

      const fromPath = location.state?.from?.pathname;
      if (response.user?.first_login) {
        navigate("/first-login");
      } else if (fromPath && fromPath !== "/login" && fromPath !== "/first-login") {
        navigate(fromPath);
      } else if (response.user?.role === "RIDER") {
        navigate("/rider");
      } else {
        navigate("/overview");
      }
    } catch (err) {
      setError(formatApiError(err, "login"));
    } finally {
      setLoading(false);
    }
  };

  const isDark = theme === "dark";
  const bgImage = isDark ? "/assets/img/dark_mode.jpg" : "/assets/img/light_mode.jpg";

  return (
    <div className="min-h-screen w-full flex flex-col lg:flex-row bg-[#F8FAFC] dark:bg-[#090A0D] text-slate-800 dark:text-slate-100 font-sans antialiased overflow-x-hidden selection:bg-[var(--brand-primary)] selection:text-white">
      {/* ---------------- SISI KIRI: HERO SECTION 60% ---------------- */}
      <div
        className="relative hidden lg:flex lg:w-[60%] flex-col justify-between p-10 xl:p-14 2xl:p-16 overflow-hidden bg-cover bg-center shrink-0 transition-all duration-500"
        style={{ backgroundImage: `url('${bgImage}')` }}
      >
        {/* Subtle Ambient Lighting Overlay */}
        <div className="absolute inset-0 bg-slate-950/15 dark:bg-black/35 pointer-events-none" />

        {/* Brand Tag (Top Left) */}
        <div className="relative z-10 flex items-center gap-3">
          <img
            src="/assets/img/kopigo_logo.jpg"
            alt="KopiGo Logo"
            className="w-10 h-10 rounded-xl object-cover shadow-sm ring-1 ring-white/20"
          />
          <span className="text-xl font-heading font-medium tracking-tight text-slate-900 dark:text-white">
            KopiGo
          </span>
        </div>

        {/* Editorial Minimalist Headline (Bottom) */}
        <div className="relative z-10 mt-auto max-w-xl">
          <h1 className="text-3xl sm:text-4xl xl:text-5xl font-heading font-medium leading-[1.2] tracking-tight text-slate-900 dark:text-white">
            Mobilitas Kopi,<br />
            <span className="text-[var(--brand-primary)]">Presisi Setiap Langkah.</span>
          </h1>
          <p className="text-sm sm:text-base text-slate-600 dark:text-slate-300/80 font-normal mt-3 max-w-md leading-relaxed">
            Sistem pendukung keputusan  zona operasional lokasi penjualan kopi keliling.
          </p>
        </div>
      </div>

      {/* ---------------- SISI KANAN: PANEL FORM LOGIN 40% ---------------- */}
      <div className="w-full lg:w-[40%] min-h-screen flex flex-col justify-between p-6 sm:p-10 lg:p-12 xl:p-14 bg-white dark:bg-[#090A0D] border-l border-slate-200/80 dark:border-white/5 transition-colors shrink-0">
        {/* Top Header Controls */}
        <div className="flex items-center justify-between w-full">
          {/* Mobile Logo Fallback */}
          <div className="flex lg:hidden items-center gap-2.5">
            <img
              src="/assets/img/kopigo_logo.jpg"
              alt="KopiGo Logo"
              className="w-8 h-8 rounded-lg object-cover shadow-xs"
            />
            <span className="text-lg font-heading font-medium tracking-tight text-slate-900 dark:text-white">
              KopiGo
            </span>
          </div>

          <div className="hidden lg:block">{/* Spacer */}</div>

          <div className="flex items-center gap-3 ml-auto">
            <ThemeToggle />
          </div>
        </div>

        {/* Center Login Form Container */}
        <div className="w-full max-w-sm sm:max-w-md mx-auto my-auto py-8">
          {/* Clean Heading */}
          <h2 className="text-2xl font-heading font-semibold text-slate-900 dark:text-white tracking-tight">
            Login
          </h2>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1 mb-6">
            Masukkan kredensial akun Anda untuk mengakses sistem.
          </p>

          {/* Status Notices */}
          {successNotice && (
            <Alert variant="success" className="mb-4 text-xs">
              {successNotice}
            </Alert>
          )}

          {warningNotice && (
            <Alert variant="warning" className="mb-4 text-xs">
              {warningNotice}
            </Alert>
          )}

          {error && (
            <Alert variant="danger" title={error.title} className="mb-4 text-xs">
              {error.message}
            </Alert>
          )}

          {/* Form */}
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div>
              <label
                htmlFor="identifier"
                className="block text-xs font-medium text-slate-700 dark:text-slate-300 mb-1.5"
              >
                Username atau Email <span className="text-[var(--brand-primary)]">*</span>
              </label>
              <div className="relative">
                <Mail className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2 pointer-events-none" />
                <input
                  id="identifier"
                  type="text"
                  {...register("identifier")}
                  placeholder="superadmin@kopigo.id"
                  autoComplete="username"
                  className={`w-full pl-10 pr-3.5 py-2.5 rounded-xl border text-sm transition-all shadow-xs bg-slate-50/50 dark:bg-[#111318] text-slate-900 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:bg-white dark:focus:bg-[#111318] focus:outline-none focus:ring-2 focus:ring-[var(--brand-primary)]/20 focus:border-[var(--brand-primary)] ${errors.identifier ? "border-red-500 focus:ring-red-500/20" : "border-slate-200 dark:border-white/10"
                    }`}
                />
              </div>
              {errors.identifier && (
                <p className="text-xs text-red-500 mt-1 font-medium">{errors.identifier.message}</p>
              )}
            </div>

            <div>
              <label
                htmlFor="password"
                className="block text-xs font-medium text-slate-700 dark:text-slate-300 mb-1.5"
              >
                Kata Sandi <span className="text-[var(--brand-primary)]">*</span>
              </label>
              <div className="relative">
                <Lock className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2 pointer-events-none" />
                <input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  {...register("password")}
                  placeholder="Masukkan kata sandi"
                  autoComplete="current-password"
                  className={`w-full pl-10 pr-10 py-2.5 rounded-xl border text-sm transition-all shadow-xs bg-slate-50/50 dark:bg-[#111318] text-slate-900 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:bg-white dark:focus:bg-[#111318] focus:outline-none focus:ring-2 focus:ring-[var(--brand-primary)]/20 focus:border-[var(--brand-primary)] ${errors.password ? "border-red-500 focus:ring-red-500/20" : "border-slate-200 dark:border-white/10"
                    }`}
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  aria-label={showPassword ? "Sembunyikan kata sandi" : "Tampilkan kata sandi"}
                  className="absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors cursor-pointer p-0.5"
                >
                  {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
              {errors.password && (
                <p className="text-xs text-red-500 mt-1 font-medium">{errors.password.message}</p>
              )}

              <div className="flex justify-end mt-1.5">
                <Link
                  to="/forgot-password"
                  className="text-xs text-[var(--brand-primary)] hover:underline font-medium transition-colors"
                >
                  Lupa kata sandi?
                </Link>
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full mt-5 py-2.5 px-4 rounded-xl bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)] active:bg-[var(--brand-primary-active)] text-white font-heading font-medium text-sm transition-colors duration-150 flex items-center justify-center gap-2 shadow-sm shadow-red-500/20 disabled:opacity-60 cursor-pointer"
            >
              {loading ? (
                "Memproses..."
              ) : (
                <>
                  Masuk <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </form>

          {/* Staff Activation Invitation Link */}
          <div className="mt-6 pt-4 border-t border-slate-100 dark:border-white/5 text-center">
            <Link
              to="/activate"
              className="text-xs text-slate-500 dark:text-slate-400 hover:text-[var(--brand-primary)] transition-colors"
            >
              Punya token aktivasi akun staf?{" "}
              <span className="text-[var(--brand-primary)] font-medium hover:underline">
                Aktivasi di sini
              </span>
            </Link>
          </div>
        </div>

        {/* Footer Credit */}
        <div className="text-center pt-4 text-xs text-slate-400 dark:text-slate-500 font-normal">
          <span>KopiGo &bull; Created by Febriyan Dwi Putra</span>
        </div>
      </div>
    </div>
  );
}

export default LoginPage;
