// single-tenant/frontend/src/pages/auth/ResetPasswordPage.jsx
import React, { useState, useEffect } from "react";
import { useNavigate, useSearchParams, Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { authService } from "@/services/authService";
import { AuthLayout } from "@/layouts/AuthLayout/AuthLayout";
import {
  Button,
  Input,
  Alert,
  Spinner,
} from "@/components/primitives";
import { FormField, FormLabel, FormErrorText } from "@/components/composites";
import { ArrowLeft, Eye, EyeOff, Check, X } from "lucide-react";

import { formatApiError } from "@/lib/errorHandler";
import {
  checkPasswordStrength,
  checkPasswordMatch,
  passwordSetupSchema,
} from "@/lib/passwordUtils";

export function ResetPasswordPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const token = searchParams.get("token");

  const [verifying, setVerifying] = useState(true);
  const [tokenData, setTokenData] = useState(null);
  const [verifyError, setVerifyError] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState(null);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(passwordSetupSchema),
    defaultValues: {
      password: "",
      confirmPassword: "",
    },
  });

  const enteredPassword = watch("password", "");
  const enteredConfirmPassword = watch("confirmPassword", "");

  const strength = checkPasswordStrength(enteredPassword);
  const matchStatus = checkPasswordMatch(enteredPassword, enteredConfirmPassword);

  useEffect(() => {
    let isMounted = true;

    async function checkToken() {
      if (!token) {
        if (isMounted) {
          setVerifying(false);
          setVerifyError({
            title: "Tautan Tidak Lengkap",
            message: "Tautan reset kata sandi tidak memiliki token valid. Silakan lakukan permintaan reset kembali.",
          });
        }
        return;
      }

      try {
        const result = await authService.verifyToken(token);
        if (isMounted) {
          if (result?.valid) {
            setTokenData(result);
          } else {
            setVerifyError(
              formatApiError(result?.reason || "Token reset kata sandi tidak valid atau telah kedaluwarsa.", "token")
            );
          }
        }
      } catch (err) {
        if (isMounted) {
          setVerifyError(formatApiError(err, "token"));
        }
      } finally {
        if (isMounted) {
          setVerifying(false);
        }
      }
    }

    checkToken();

    return () => {
      isMounted = false;
    };
  }, [token]);

  const onSubmit = async (data) => {
    setSubmitting(true);
    setSubmitError(null);

    try {
      await authService.resetPassword({
        token,
        password: data.password,
      });

      navigate("/login?reset=true", { replace: true });
    } catch (err) {
      setSubmitError(formatApiError(err, "reset-password"));
    } finally {
      setSubmitting(false);
    }
  };

  const confirmTrailingElement = (
    <div className="flex items-center gap-1.5 pr-0.5">
      {matchStatus.status === "match" && (
        <span
          title="Kata sandi cocok"
          data-testid="password-match-indicator"
          className="inline-flex items-center text-emerald-500"
        >
          <Check className="w-4 h-4" />
        </span>
      )}
      {matchStatus.status === "mismatch" && (
        <span
          title="Kata sandi belum cocok"
          data-testid="password-mismatch-indicator"
          className="inline-flex items-center text-red-400"
        >
          <X className="w-4 h-4" />
        </span>
      )}
      <button
        type="button"
        onClick={() => setShowConfirmPassword(!showConfirmPassword)}
        aria-label={showConfirmPassword ? "Sembunyikan kata sandi" : "Tampilkan kata sandi"}
        className="p-1 rounded text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors cursor-pointer"
      >
        {showConfirmPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
      </button>
    </div>
  );

  return (
    <AuthLayout
      title="Atur Ulang Kata Sandi"
      subtitle="Buat kata sandi baru untuk akun Anda"
    >
      {verifying ? (
        <div className="py-12 flex flex-col items-center justify-center text-center space-y-3">
          <Spinner size="lg" />
          <p className="text-xs text-slate-500 dark:text-slate-400 font-mono">Memverifikasi keabsahan token reset...</p>
        </div>
      ) : verifyError ? (
        <div className="space-y-4">
          <Alert variant="danger" title={verifyError.title} className="text-xs">
            {verifyError.message}
          </Alert>

          <div className="pt-2 flex flex-col gap-2">
            <Link to="/forgot-password">
              <Button variant="primary" size="lg" className="w-full">
                Kirim Ulang Tautan Reset
              </Button>
            </Link>
            <Link to="/login">
              <Button variant="outline" size="lg" className="w-full">
                Kembali ke Halaman Login
              </Button>
            </Link>
          </div>
        </div>
      ) : (
        <div>
          {tokenData?.email && (
            <div className="mb-4 p-3.5 rounded-xl bg-slate-50/50 dark:bg-[#111318] border border-slate-200/80 dark:border-white/10 text-xs">
              <span className="text-[10px] text-slate-400 uppercase font-mono block">Akun</span>
              <span className="font-medium text-slate-900 dark:text-white font-mono">{tokenData.email}</span>
            </div>
          )}

          {submitError && (
            <Alert variant="danger" title={submitError.title} className="mb-4 text-xs">
              {submitError.message}
            </Alert>
          )}

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <FormField error={!!errors.password}>
              <FormLabel htmlFor="password" required>Kata Sandi Baru</FormLabel>
              <Input
                id="password"
                type={showPassword ? "text" : "password"}
                {...register("password")}
                trailingElement={
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    aria-label={showPassword ? "Sembunyikan kata sandi" : "Tampilkan kata sandi"}
                    className="p-1 rounded text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors cursor-pointer"
                  >
                    {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                }
                placeholder="Minimal 8 karakter (kombinasi huruf & angka)"
                autoComplete="new-password"
              />
              {errors.password && <FormErrorText>{errors.password.message}</FormErrorText>}
            </FormField>

            {/* Minimal Strength Indicator */}
            {enteredPassword.length > 0 && (
              <div className="space-y-1.5 p-3 rounded-xl bg-slate-50/50 dark:bg-[#111318] border border-slate-200/80 dark:border-white/10">
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-400 text-[11px]">Kekuatan Sandi</span>
                  <span className="font-semibold text-slate-900 dark:text-white text-xs">{strength.label}</span>
                </div>
                <div className="grid grid-cols-3 gap-1.5 h-1.5 w-full">
                  <div className={`h-full rounded-full transition-all duration-200 ${strength.score >= 1 ? strength.color : "bg-slate-200 dark:bg-zinc-800"}`} />
                  <div className={`h-full rounded-full transition-all duration-200 ${strength.score >= 2 ? strength.color : "bg-slate-200 dark:bg-zinc-800"}`} />
                  <div className={`h-full rounded-full transition-all duration-200 ${strength.score >= 3 ? strength.color : "bg-slate-200 dark:bg-zinc-800"}`} />
                </div>
              </div>
            )}

            <FormField error={!!errors.confirmPassword}>
              <FormLabel htmlFor="confirmPassword" required>Konfirmasi Kata Sandi Baru</FormLabel>
              <Input
                id="confirmPassword"
                type={showConfirmPassword ? "text" : "password"}
                {...register("confirmPassword")}
                trailingElement={confirmTrailingElement}
                placeholder="Ulangi kata sandi baru"
                autoComplete="new-password"
              />
              {matchStatus.status === "match" && !errors.confirmPassword && (
                <span className="text-[11px] text-emerald-500 font-medium flex items-center gap-1 mt-1">
                  <Check className="w-3.5 h-3.5" /> Kata sandi cocok
                </span>
              )}
              {errors.confirmPassword && <FormErrorText>{errors.confirmPassword.message}</FormErrorText>}
            </FormField>

            <Button
              type="submit"
              variant="primary"
              size="lg"
              loading={submitting}
              className="w-full mt-4"
            >
              Perbarui Kata Sandi
            </Button>
          </form>

          <div className="mt-6 pt-4 border-t border-slate-100 dark:border-white/5 text-center">
            <Link
              to="/login"
              className="inline-flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400 hover:text-[var(--brand-primary)] transition-colors"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              Kembali ke Halaman Login
            </Link>
          </div>
        </div>
      )}
    </AuthLayout>
  );
}

export default ResetPasswordPage;

// multi-tenant/frontend/design_backup/pages/auth/ResetPasswordPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { authService } from "../../services/authService";
  import { Lock, CheckCircle2, ArrowRight, ArrowLeft, KeyRound, Check, ShieldCheck } from "lucide-svelte";
  import Button from "../../components/ui/Button.svelte";
  import Input from "../../components/ui/Input.svelte";
  import Alert from "../../components/ui/Alert.svelte";

  interface Props {
    onNavigate: (route: string) => void;
    tokenParam?: string | null;
  }

  let { onNavigate, tokenParam = null }: Props = $props();

  let token = $state<string | null>(null);
  let verifying = $state(true);
  let tokenValid = $state(false);

  let newPassword = $state("");
  let confirmPassword = $state("");

  let successMsg = $state<string | null>(null);
  let errorMsg = $state<string | null>(null);
  let loading = $state(false);

  let passwordError = $state<string | null>(null);
  let confirmError = $state<string | null>(null);

  // Real-time password validation indicators
  let hasMinLength = $derived(newPassword.length >= 8);
  let hasUppercase = $derived(/[A-Z]/.test(newPassword));
  let hasNumber = $derived(/[0-9]/.test(newPassword));
  let isMatching = $derived(newPassword.length > 0 && newPassword === confirmPassword);

  onMount(async () => {
    let currentToken = tokenParam;
    if (!currentToken) {
      const urlParams = new URLSearchParams(window.location.search);
      currentToken = urlParams.get("token");
    }

    if (!currentToken) {
      errorMsg = "Token reset kata sandi tidak ditemukan pada URL.";
      verifying = false;
      return;
    }

    token = currentToken;
    try {
      await authService.verifyResetToken(currentToken);
      tokenValid = true;
    } catch (err: any) {
      errorMsg =
        err?.response?.data?.msg ||
        err?.response?.data?.message ||
        "Token reset kata sandi tidak valid atau sudah kedaluwarsa.";
    } finally {
      verifying = false;
    }
  });

  const handleSubmit = async (e?: Event) => {
    if (e) e.preventDefault();
    passwordError = null;
    confirmError = null;

    if (!newPassword || newPassword.length < 8) {
      passwordError = "Password minimal 8 karakter";
      return;
    }
    if (!/[A-Z]/.test(newPassword)) {
      passwordError = "Password harus mengandung minimal 1 huruf besar (A-Z)";
      return;
    }
    if (!/[0-9]/.test(newPassword)) {
      passwordError = "Password harus mengandung minimal 1 angka (0-9)";
      return;
    }
    if (newPassword !== confirmPassword) {
      confirmError = "Konfirmasi password tidak cocok dengan password baru";
      return;
    }

    if (!token) {
      errorMsg = "Token reset tidak ditemukan.";
      return;
    }

    loading = true;
    errorMsg = null;

    try {
      await authService.resetPassword({ token, password: newPassword });
      successMsg = "Kata sandi Anda berhasil diperbarui. Mengarahkan ke halaman login...";
      setTimeout(() => onNavigate("/login"), 2000);
    } catch (err: any) {
      errorMsg =
        err?.response?.data?.msg ||
        err?.response?.data?.message ||
        err?.message ||
        "Gagal memperbarui kata sandi.";
    } finally {
      loading = false;
    }
  };
</script>

<div class="min-h-screen bg-[#09090B] pattern-dots-dark relative flex flex-col justify-center py-10 sm:py-14 px-4 sm:px-6 lg:px-8 font-outfit-400 select-none overflow-x-hidden">
  <!-- Ambient Lighting Effects -->
  <div class="fixed top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-[#FF634A]/10 rounded-full blur-[120px] pointer-events-none"></div>
  <div class="fixed bottom-10 right-10 w-72 h-72 bg-emerald-950/20 rounded-full blur-[90px] pointer-events-none"></div>

  <!-- Massive Typographic Background MOVA with Dark Blur (Outfit font) -->
  <div
    class="fixed inset-0 flex items-center justify-center select-none pointer-events-none z-0 overflow-hidden"
  >
    <span
      class="text-[14rem] sm:text-[20rem] md:text-[26rem] font-outfit-800 font-extrabold tracking-tighter text-white/[0.035] blur-[2px] leading-none select-none"
    >
      MOVA
    </span>
  </div>

  <div class="sm:mx-auto sm:w-full sm:max-w-md relative z-10">
    <!-- Brand Header MOVA (Typography Outfit Text Only) -->
    <div class="text-center space-y-1 mb-7">
      <h1 class="text-3xl sm:text-4xl font-outfit-800 font-extrabold text-white tracking-tight">
        MOVA
      </h1>
      <p class="text-xs text-[#FF8573] font-outfit-600 tracking-wide">
        Move Where Demand Is.
      </p>
      <p class="text-[11px] text-[#71717A]">
        Setel Ulang Kata Sandi
      </p>
    </div>

    <!-- Main Card Container -->
    <div class="bg-[#131316]/95 backdrop-blur-xl py-7 px-6 sm:px-8 rounded-3xl border border-[#24242A] shadow-2xl space-y-5">
      {#if verifying}
        <div class="py-10 flex flex-col items-center justify-center space-y-3">
          <div class="w-9 h-9 border-3 border-[#FF634A] border-t-transparent rounded-full animate-spin"></div>
          <span class="text-xs text-[#A1A1AA] font-outfit-600">Memvalidasi token reset kata sandi...</span>
        </div>
      {:else}
        {#if successMsg}
          <Alert variant="success" title="Pembaruan Berhasil">
            {successMsg}
          </Alert>

          <Button
            type="button"
            onclick={() => onNavigate("/login")}
            variant="primary"
            size="md"
            class="w-full py-3.5 font-outfit-600"
            rightIcon={ArrowRight}
          >
            Masuk Sekarang
          </Button>
        {/if}

        {#if errorMsg}
          <Alert variant="danger" title="Kendala Validasi">
            {errorMsg}
          </Alert>
        {/if}

        {#if tokenValid && !successMsg}
          <form onsubmit={handleSubmit} class="space-y-4">
            <Input
              label="Kata Sandi Baru"
              type="password"
              leftIcon={Lock}
              placeholder="••••••••"
              required
              error={passwordError}
              bind:value={newPassword}
            />

            <Input
              label="Konfirmasi Kata Sandi Baru"
              type="password"
              leftIcon={KeyRound}
              placeholder="••••••••"
              required
              error={confirmError}
              bind:value={confirmPassword}
            />

            <!-- Real-time Password Strength Requirements Checklist -->
            <div class="p-3 bg-[#1A1A1F] rounded-2xl border border-[#272730] space-y-1.5 text-[11px]">
              <div class="font-outfit-600 text-[#A1A1AA] mb-1">Ketentuan Keamanan Sandi:</div>
              <div class="grid grid-cols-2 gap-1.5">
                <div class="flex items-center gap-1.5 {hasMinLength ? 'text-emerald-400 font-semibold' : 'text-[#71717A]'}">
                  {#if hasMinLength}<Check class="w-3.5 h-3.5" />{:else}<span class="w-1.5 h-1.5 rounded-full bg-[#52525B]"></span>{/if}
                  <span>Minimal 8 Karakter</span>
                </div>
                <div class="flex items-center gap-1.5 {hasUppercase ? 'text-emerald-400 font-semibold' : 'text-[#71717A]'}">
                  {#if hasUppercase}<Check class="w-3.5 h-3.5" />{:else}<span class="w-1.5 h-1.5 rounded-full bg-[#52525B]"></span>{/if}
                  <span>Huruf Besar (A-Z)</span>
                </div>
                <div class="flex items-center gap-1.5 {hasNumber ? 'text-emerald-400 font-semibold' : 'text-[#71717A]'}">
                  {#if hasNumber}<Check class="w-3.5 h-3.5" />{:else}<span class="w-1.5 h-1.5 rounded-full bg-[#52525B]"></span>{/if}
                  <span>Mengandung Angka</span>
                </div>
                <div class="flex items-center gap-1.5 {isMatching ? 'text-emerald-400 font-semibold' : 'text-[#71717A]'}">
                  {#if isMatching}<Check class="w-3.5 h-3.5" />{:else}<span class="w-1.5 h-1.5 rounded-full bg-[#52525B]"></span>{/if}
                  <span>Sandi Cocok</span>
                </div>
              </div>
            </div>

            <Button
              type="submit"
              variant="primary"
              size="md"
              isPending={loading}
              class="w-full py-3.5 font-outfit-600"
              rightIcon={ArrowRight}
            >
              {loading ? "Menyimpan Kata Sandi..." : "Perbarui Kata Sandi"}
            </Button>
          </form>
        {/if}

        <div class="pt-2 border-t border-[#24242A] text-center">
          <button
            type="button"
            onclick={() => onNavigate("/login")}
            class="inline-flex items-center gap-1.5 text-xs text-[#A1A1AA] hover:text-white font-outfit-600 transition-colors cursor-pointer py-1"
          >
            <ArrowLeft class="w-3.5 h-3.5 text-[#FF634A]" /> Kembali ke Halaman Masuk
          </button>
        </div>
      {/if}
    </div>
  </div>
</div>
