// multi-tenant/frontend/design_backup/components/ui/Button.svelte
<script lang="ts">
  import { Loader2 } from 'lucide-svelte';

  interface Props {
    type?: 'button' | 'submit' | 'reset';
    variant?: 'primary' | 'secondary' | 'outline' | 'danger' | 'ghost' | 'white';
    size?: 'sm' | 'md' | 'lg';
    isPending?: boolean;
    loading?: boolean;
    disabled?: boolean;
    leftIcon?: any;
    rightIcon?: any;
    class?: string;
    onclick?: (e: MouseEvent) => void;
    children?: any;
  }

  let {
    type = 'button',
    variant = 'primary',
    size = 'md',
    isPending = false,
    loading = false,
    disabled = false,
    leftIcon: LeftIcon,
    rightIcon: RightIcon,
    class: className = '',
    onclick,
    children,
  }: Props = $props();

  const isSpinning = $derived(isPending || loading);

  const variantStyles = {
    primary: 'bg-gradient-to-r from-[#FF634A] to-[#FF8573] hover:brightness-110 active:brightness-95 text-[#09090B] font-outfit-600 shadow-lg shadow-[#FF634A]/25 border border-white/20',
    secondary: 'bg-[#1F1F24] hover:bg-[#272730] active:bg-[#1A1A1F] text-white border border-[#2E2E38] font-outfit-600',
    outline: 'bg-transparent hover:bg-[#1F1F24] active:bg-[#16161A] text-[#D4D4D8] hover:text-white border border-[#2E2E38] hover:border-[#3E3E4A]',
    danger: 'bg-rose-600 hover:bg-rose-500 active:bg-rose-700 text-white shadow-lg shadow-rose-900/30 border border-rose-500/30',
    ghost: 'bg-transparent hover:bg-[#1F1F24] text-[#A1A1AA] hover:text-white',
    white: 'bg-white hover:bg-zinc-100 active:bg-zinc-200 text-[#09090B] font-outfit-600 shadow-lg shadow-black/20 border border-white/80',
  };

  const sizeStyles = {
    sm: 'px-3.5 py-2 text-xs rounded-xl gap-1.5',
    md: 'px-4.5 py-3 text-sm rounded-2xl gap-2',
    lg: 'px-6 py-3.5 text-base rounded-2xl gap-2.5',
  };
</script>

<button
  {type}
  disabled={disabled || isSpinning}
  {onclick}
  class="inline-flex items-center justify-center font-outfit-600 tracking-tight transition-all duration-200 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed active:scale-[0.98] {variantStyles[variant]} {sizeStyles[size]} {className}"
>
  {#if isSpinning}
    <Loader2 class="w-4 h-4 animate-spin shrink-0" />
  {:else if LeftIcon}
    <LeftIcon class="w-4 h-4 shrink-0" />
  {/if}

  <span>
    {@render children?.()}
  </span>

  {#if !isSpinning && RightIcon}
    <RightIcon class="w-4 h-4 shrink-0" />
  {/if}
</button>

// single-tenant/frontend/src/components/primitives/Button.jsx
import React from "react";
import { cn } from "@/lib/utils";
import { Loader2 } from "lucide-react";

export function Button({
  children,
  variant = "primary",
  size = "md",
  loading = false,
  disabled = false,
  leadingIcon: LeadingIcon,
  trailingIcon: TrailingIcon,
  className,
  type = "button",
  ...props
}) {
  const variantStyles = {
    primary: "bg-[var(--accent-primary)] hover:bg-[var(--accent-primary-hover)] text-white border border-transparent font-medium shadow-xs",
    secondary: "bg-[var(--surface-raised)] hover:bg-[var(--surface-muted)] text-[var(--text-primary)] border border-[var(--border-subtle)] font-medium",
    danger: "bg-[var(--status-danger)] hover:opacity-90 text-white border border-transparent font-medium shadow-xs",
    ghost: "bg-transparent hover:bg-[var(--surface-raised)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] border border-transparent",
    outline: "bg-transparent hover:bg-[var(--surface-raised)] text-[var(--text-primary)] border border-[var(--border)] font-medium",
  }[variant] || "bg-[var(--accent-primary)] text-white";

  const sizeStyles = {
    sm: "h-8 px-3 text-xs gap-1.5 rounded-[var(--radius-md)]",
    md: "h-9 px-4 text-sm gap-2 rounded-[var(--radius-md)]",
    lg: "h-11 px-5 text-base gap-2.5 rounded-[var(--radius-lg)] min-h-[44px]", // 44px touch target for Rider
  }[size] || "h-9 px-4 text-sm gap-2";

  return (
    <button
      type={type}
      disabled={disabled || loading}
      className={cn(
        "inline-flex items-center justify-center transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-primary)] focus-visible:ring-offset-1 disabled:opacity-50 disabled:cursor-not-allowed select-none active:scale-[0.98] cursor-pointer",
        variantStyles,
        sizeStyles,
        className
      )}
      {...props}
    >
      {loading ? (
        <Loader2 className="w-4 h-4 animate-spin shrink-0" aria-hidden="true" />
      ) : LeadingIcon ? (
        <LeadingIcon className="w-4 h-4 shrink-0" aria-hidden="true" />
      ) : null}
      <span className="truncate">{children}</span>
      {!loading && TrailingIcon ? (
        <TrailingIcon className="w-4 h-4 shrink-0" aria-hidden="true" />
      ) : null}
    </button>
  );
}

export function IconButton({
  icon: Icon,
  label,
  variant = "ghost",
  size = "md",
  loading = false,
  disabled = false,
  className,
  type = "button",
  ...props
}) {
  const sizeStyles = {
    sm: "w-8 h-8 text-xs p-1.5 rounded-[var(--radius-md)]",
    md: "w-9 h-9 text-sm p-2 rounded-[var(--radius-md)]",
    lg: "w-11 h-11 text-base p-2.5 rounded-[var(--radius-lg)] min-w-[44px] min-h-[44px]",
  }[size] || "w-9 h-9 p-2";

  const variantStyles = {
    primary: "bg-[var(--accent-primary)] hover:bg-[var(--accent-primary-hover)] text-white border border-transparent",
    secondary: "bg-[var(--surface-raised)] hover:bg-[var(--surface-muted)] text-[var(--text-primary)] border border-[var(--border-subtle)]",
    danger: "bg-[var(--status-danger)] hover:opacity-90 text-white border border-transparent",
    ghost: "bg-transparent hover:bg-[var(--surface-raised)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] border border-transparent",
    outline: "bg-transparent hover:bg-[var(--surface-raised)] text-[var(--text-primary)] border border-[var(--border)]",
  }[variant] || "bg-transparent text-[var(--text-secondary)]";

  return (
    <button
      type={type}
      aria-label={label}
      title={label}
      disabled={disabled || loading}
      className={cn(
        "inline-flex items-center justify-center transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-primary)] disabled:opacity-50 disabled:cursor-not-allowed select-none active:scale-[0.96] cursor-pointer",
        variantStyles,
        sizeStyles,
        className
      )}
      {...props}
    >
      {loading ? (
        <Loader2 className="w-4 h-4 animate-spin" aria-hidden="true" />
      ) : Icon ? (
        <Icon className="w-4 h-4" aria-hidden="true" />
      ) : null}
    </button>
  );
}
