// single-tenant/frontend/src/components/primitives/Input.jsx
import React, { forwardRef } from "react";
import { cn } from "@/lib/utils";

export const Input = forwardRef(function Input(
  {
    className,
    type = "text",
    variant = "default",
    invalid = false,
    leadingIcon: LeadingIcon,
    trailingIcon: TrailingIcon,
    trailingElement,
    size = "md",
    ...props
  },
  ref
) {
  const sizeStyles = {
    sm: "h-8 text-xs px-2.5 rounded-lg",
    md: "h-10 text-sm px-3.5 rounded-xl",
    lg: "h-11 text-sm px-4 rounded-xl min-h-[44px]",
  }[size] || "h-10 text-sm px-3.5 rounded-xl";

  const variantStyles = {
    default: "bg-slate-50/50 dark:bg-[#111318] border-slate-200 dark:border-white/10 text-slate-900 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500",
    recessed: "bg-[var(--surface-muted)]/70 border-[var(--border-subtle)] focus:bg-white dark:focus:bg-[#111318]",
  }[variant] || "bg-slate-50/50 dark:bg-[#111318] border-slate-200 dark:border-white/10 text-slate-900 dark:text-slate-100";

  return (
    <div className="relative flex items-center w-full">
      {LeadingIcon && (
        <div className="absolute left-3.5 flex items-center pointer-events-none text-slate-400">
          <LeadingIcon className="w-4 h-4" aria-hidden="true" />
        </div>
      )}
      <input
        type={type}
        ref={ref}
        aria-invalid={invalid}
        className={cn(
          "w-full border text-sm transition-all duration-150 focus:outline-none focus:border-[var(--brand-primary)] focus:ring-2 focus:ring-[var(--brand-primary)]/20 disabled:opacity-50 disabled:cursor-not-allowed shadow-xs",
          variantStyles,
          sizeStyles,
          LeadingIcon && "pl-10",
          (TrailingIcon || trailingElement) && "pr-10",
          invalid && "border-red-500 focus:border-red-500 focus:ring-red-500/20",
          className
        )}
        {...props}
      />
      {TrailingIcon && !trailingElement && (
        <div className="absolute right-3 flex items-center pointer-events-none text-[var(--text-muted)]">
          <TrailingIcon className="w-4 h-4" aria-hidden="true" />
        </div>
      )}
      {trailingElement && (
        <div className="absolute right-2.5 flex items-center">
          {trailingElement}
        </div>
      )}
    </div>
  );
});

export const Textarea = forwardRef(function Textarea(
  { className, invalid = false, rows = 3, ...props },
  ref
) {
  return (
    <textarea
      ref={ref}
      rows={rows}
      aria-invalid={invalid}
      className={cn(
        "w-full bg-[var(--surface-raised)] border border-[var(--border)] text-[var(--text-primary)] placeholder:text-[var(--text-muted)] rounded-[var(--radius-md)] p-3 text-sm transition-all focus:outline-none focus:border-[var(--accent-primary)] focus:ring-1 focus:ring-[var(--accent-primary)] disabled:opacity-50 disabled:cursor-not-allowed resize-y",
        invalid && "border-[var(--status-danger)] focus:border-[var(--status-danger)] focus:ring-[var(--status-danger)]",
        className
      )}
      {...props}
    />
  );
});

// multi-tenant/frontend/src/components/ui/input/Input.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLInputAttributes } from "svelte/elements";
  import type { Snippet } from "svelte";

  interface InputProps extends HTMLInputAttributes {
    class?: string;
    value?: string | number;
    icon?: string; // Boxicon name, e.g. "bx-search", "bx-envelope", "bx-lock"
    hotkey?: string; // e.g. "Ctrl K" or "⌘K"
    error?: string;
    suffix?: Snippet;
  }

  let {
    class: className = "",
    value = $bindable(),
    type = "text",
    icon,
    hotkey,
    error,
    suffix,
    disabled = false,
    ...restProps
  }: InputProps = $props();
</script>

<div class="relative w-full">
  {#if icon}
    <div class="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-500">
      <i class={cn("bx text-lg leading-none", icon)}></i>
    </div>
  {/if}

  <input
    {type}
    {disabled}
    bind:value
    class={cn(
      "flex h-10 w-full rounded-lg border border-white/10 bg-[#121215] px-3.5 py-2 text-sm text-[#fafafa] placeholder:text-zinc-500 shadow-inner transition-all duration-150 ease-in-out focus:border-[#FF634A] focus:outline-none focus:ring-1 focus:ring-[#FF634A] disabled:cursor-not-allowed disabled:opacity-50 [color-scheme:dark]",
      icon && "pl-10",
      hotkey && "pr-16",
      error && "border-red-500/80 focus:border-red-500 focus:ring-red-500",
      className
    )}
    {...restProps}
  />

  {#if hotkey}
    <div class="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 flex items-center rounded border border-white/10 bg-[#1e1e22] px-1.5 py-0.5 font-mono text-[10px] text-zinc-400">
      {hotkey}
    </div>
  {/if}

  {#if suffix}
    <div class="absolute right-3 top-1/2 -translate-y-1/2">
      {@render suffix()}
    </div>
  {/if}

  {#if error}
    <p class="mt-1 text-xs text-red-400">{error}</p>
  {/if}
</div>
